site_name: mtg_pynance
theme:
  name: material
  palette:
    scheme: slate
    primary: brown

nav:
  - Home: index.md
  - How does it work?: explanation.md
  - Installation: installation.md
  - User guide:
    - Create your collection's CSV file: user_guide/csv_file_creation.md
  - API:
    - Analysis: api/analysis.md
    - Collection: api/collection.md
    - Config: api/config.md
    - Database: api/database.md
    - Retrieval: api/retrieval.md
  - Acknowledgemnts: acknowledgements.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            docstring_style: numpy
