site_name: MTG Pynance
theme:
  name: material

nav:
  - Home: index.md
  - User guide:
    - Installation: user_guide/installation.md
    - Getting started: user_guide/getting_started.md
  - API:
    - analysis.md
    - collection.md
    - config.md
    - database.md
    - retrieval.md
  - Acknowledgemnts: acknowledgements.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            docstring_style: numpy
