site_name: mtg_pynance
theme:
  name: material
  palette:
    scheme: slate
    primary: brown
  
extra_css:
  - style_sheets/extra.css

nav:
  - Home: index.md
  - How does it work?: explanation.md
  - Installation: installation.md
  - User guide:
    - Create your collection's CSV file: user_guide/csv_file_creation.md
    - Make the run file: user_guide/run_file_creation.md
    - Analyze your collection: user_guide/collection_analysis.md
  - API:
    - Analysis: api/analysis.md
    - Collection: api/collection.md
    - Config: api/config.md
    - Database: api/database.md
    - Retrieval: api/retrieval.md
  - Acknowledgements: acknowledgements.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
