site_name: MTG Pynance
theme:
  name: material
  palette:
    scheme: slate
    primary: brown

nav:
  - Home: index.md
  - How does it work?: explanation.md
  - Installation: installation.md
  - User guide:
    - Installation: user_guide/installation.md
    - Create your collection's CSV file: user_guide/csv_file_creation.md
  - API:
    - analysis.md
    - collection.md
    - config.md
    - database.md
    - retrieval.md
  - Acknowledgemnts: acknowledgements.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            docstring_style: numpy
