name: Publish
run-name: ${{ github.actor }} Publishing to PyPI
on:
    release:
        types:
            - released
jobs:
    publish:
        name: Publish Release to PyPI
        runs-on: ubuntu-latest
        environment: release
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: pdm-project/setup-pdm@v4
            - name: Show package version
              run: |
                grep version pyproject.toml
                pdm show --version
                ls -la dist/ || true
            - name: Publish packages to PyPI
              run: pdm publish
